services:
  - type: web
    name: whatsaly
    runtime: docker
    branch: master
    repo: https://github.com/astrox11/Whatsaly
    healthCheckPath: /

    envVars:
      - key: BOT_NAME
        sync: false
      - key: DEBUG
        sync: false
